import type { Config } from "tailwindcss";
import typography from "@tailwindcss/typography";

export default {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "success-light": "#3B6939",
        "success-light-on": "#FFFFFF",
        "success-light-container": "#BCF0B4",
        "success-light-on-container": "#002204",
        "success-dark": "#A1D39A",
        "success-dark-on": "#0A390F",
        "success-dark-container": "#235024",
        "success-dark-on-container": "#BCF0B4",
        "warning-light": "#775A0B",
        "warning-light-on": "#FFFFFF",
        "warning-light-container": "#FFDF9E",
        "warning-light-on-container": "#261A00",
        "warning-dark": "#E9C16C",
        "warning-dark-on": "#3F2E00",
        "warning-dark-container": "#5B4300",
        "warning-dark-on-container": "#FFDF9E",
        "info-light": "#36618E",
        "info-light-on": "#FFFFFF",
        "info-light-container": "#D1E4FF",
        "info-light-on-container": "#001D36",
        "info-dark": "#A0CAFD",
        "info-dark-on": "#003258",
        "info-dark-container": "#194975",
        "info-dark-on-container": "#D1E4FF",
        "attention-light": "#685F12",
        "attention-light-on": "#FFFFFF",
        "attention-light-container": "#F1E48A",
        "attention-light-on-container": "#201C00",
        "attention-dark": "#D4C871",
        "attention-dark-on": "#363100",
        "attention-dark-container": "#4F4800",
        "attention-dark-on-container": "#F1E48A",
        "error-light": "#B3261E",
        "error-light-on": "#FFFFFF",
        "error-light-container": "#FFDAD6",
        "error-light-on-container": "#410002",
        "error-dark": "#FFB4AB",
        "error-dark-on": "#690005",
        "error-dark-container": "#93000A",
        light: {
          primary: "#1E40AF",
          surfaceTint: "#1E40AF",
          onPrimary: "#FFFFFF",
          primaryContainer: "#DBEAFE",
          onPrimaryContainer: "#1E3A8A",
          secondary: "#0891B2",
          onSecondary: "#FFFFFF",
          secondaryContainer: "#CFFAFE",
          onSecondaryContainer: "#155E75",
          tertiary: "#F59E0B",
          onTertiary: "#FFFFFF",
          tertiaryContainer: "#FEF3C7",
          onTertiaryContainer: "#92400E",
          error: "#BA1A1A",
          onError: "#FFFFFF",
          errorContainer: "#FFDAD6",
          onErrorContainer: "#93000A",
          background: "#F8FAFC",
          onBackground: "#0F172A",
          surface: "#F8FAFC",
          onSurface: "#0F172A",
          surfaceVariant: "#E2E8F0",
          onSurfaceVariant: "#334155",
          outline: "#64748B",
          outlineVariant: "#CBD5E1",
          shadow: "#000000",
          scrim: "#000000",
          inverseSurface: "#1E293B",
          inverseOnSurface: "#F1F5F9",
          inversePrimary: "#93C5FD",
          primaryFixed: "#DBEAFE",
          onPrimaryFixed: "#1E3A8A",
          primaryFixedDim: "#93C5FD",
          onPrimaryFixedVariant: "#1E40AF",
          secondaryFixed: "#CFFAFE",
          onSecondaryFixed: "#155E75",
          secondaryFixedDim: "#67E8F9",
          onSecondaryFixedVariant: "#0891B2",
          tertiaryFixed: "#FEF3C7",
          onTertiaryFixed: "#92400E",
          tertiaryFixedDim: "#FCD34D",
          onTertiaryFixedVariant: "#D97706",
          surfaceDim: "#E2E8F0",
          surfaceBright: "#F8FAFC",
          surfaceContainerLowest: "#FFFFFF",
          surfaceContainerLow: "#F1F5F9",
          surfaceContainer: "#E2E8F0",
          surfaceContainerHigh: "#CBD5E1",
          surfaceContainerHighest: "#B4BCC9",
        },
        "light-medium-contrast": {
          primary: "#1E3A8A",
          surfaceTint: "#1E40AF",
          onPrimary: "#FFFFFF",
          primaryContainer: "#2563EB",
          onPrimaryContainer: "#FFFFFF",
          secondary: "#0E7490",
          onSecondary: "#FFFFFF",
          secondaryContainer: "#06B6D4",
          onSecondaryContainer: "#FFFFFF",
          tertiary: "#D97706",
          onTertiary: "#FFFFFF",
          tertiaryContainer: "#F59E0B",
          onTertiaryContainer: "#FFFFFF",
          error: "#8C0009",
          onError: "#FFFFFF",
          errorContainer: "#DA342E",
          onErrorContainer: "#FFFFFF",
          background: "#F8FAFC",
          onBackground: "#0F172A",
          surface: "#F8FAFC",
          onSurface: "#0F172A",
          surfaceVariant: "#E2E8F0",
          onSurfaceVariant: "#1E293B",
          outline: "#475569",
          outlineVariant: "#64748B",
          shadow: "#000000",
          scrim: "#000000",
          inverseSurface: "#1E293B",
          inverseOnSurface: "#F1F5F9",
          inversePrimary: "#93C5FD",
          primaryFixed: "#2563EB",
          onPrimaryFixed: "#FFFFFF",
          primaryFixedDim: "#1E40AF",
          onPrimaryFixedVariant: "#FFFFFF",
          secondaryFixed: "#06B6D4",
          onSecondaryFixed: "#FFFFFF",
          secondaryFixedDim: "#0891B2",
          onSecondaryFixedVariant: "#FFFFFF",
          tertiaryFixed: "#F59E0B",
          onTertiaryFixed: "#FFFFFF",
          tertiaryFixedDim: "#D97706",
          onTertiaryFixedVariant: "#FFFFFF",
          surfaceDim: "#CBD5E1",
          surfaceBright: "#F8FAFC",
          surfaceContainerLowest: "#FFFFFF",
          surfaceContainerLow: "#F1F5F9",
          surfaceContainer: "#E2E8F0",
          surfaceContainerHigh: "#CBD5E1",
          surfaceContainerHighest: "#B4BCC9",
        },
        "light-high-contrast": {
          primary: "#172554",
          surfaceTint: "#1E40AF",
          onPrimary: "#FFFFFF",
          primaryContainer: "#1E3A8A",
          onPrimaryContainer: "#FFFFFF",
          secondary: "#164E63",
          onSecondary: "#FFFFFF",
          secondaryContainer: "#0E7490",
          onSecondaryContainer: "#FFFFFF",
          tertiary: "#78350F",
          onTertiary: "#FFFFFF",
          tertiaryContainer: "#92400E",
          onTertiaryContainer: "#FFFFFF",
          error: "#600004",
          onError: "#FFFFFF",
          errorContainer: "#8C0009",
          onErrorContainer: "#FFFFFF",
          background: "#F8FAFC",
          onBackground: "#000000",
          surface: "#F8FAFC",
          onSurface: "#000000",
          surfaceVariant: "#E2E8F0",
          onSurfaceVariant: "#000000",
          outline: "#1E293B",
          outlineVariant: "#334155",
          shadow: "#000000",
          scrim: "#000000",
          inverseSurface: "#1E293B",
          inverseOnSurface: "#FFFFFF",
          inversePrimary: "#DBEAFE",
          primaryFixed: "#1E3A8A",
          onPrimaryFixed: "#FFFFFF",
          primaryFixedDim: "#1E40AF",
          onPrimaryFixedVariant: "#FFFFFF",
          secondaryFixed: "#0E7490",
          onSecondaryFixed: "#FFFFFF",
          secondaryFixedDim: "#0891B2",
          onSecondaryFixedVariant: "#FFFFFF",
          tertiaryFixed: "#92400E",
          onTertiaryFixed: "#FFFFFF",
          tertiaryFixedDim: "#B45309",
          onTertiaryFixedVariant: "#FFFFFF",
          surfaceDim: "#B4BCC9",
          surfaceBright: "#F8FAFC",
          surfaceContainerLowest: "#FFFFFF",
          surfaceContainerLow: "#F1F5F9",
          surfaceContainer: "#E2E8F0",
          surfaceContainerHigh: "#CBD5E1",
          surfaceContainerHighest: "#B4BCC9",
        },
        dark: {
          primary: "#93C5FD",
          surfaceTint: "#93C5FD",
          onPrimary: "#1E3A8A",
          primaryContainer: "#1E40AF",
          onPrimaryContainer: "#DBEAFE",
          secondary: "#67E8F9",
          onSecondary: "#164E63",
          secondaryContainer: "#0891B2",
          onSecondaryContainer: "#CFFAFE",
          tertiary: "#FCD34D",
          onTertiary: "#78350F",
          tertiaryContainer: "#D97706",
          onTertiaryContainer: "#FEF3C7",
          error: "#FFB4AB",
          onError: "#690005",
          errorContainer: "#93000A",
          onErrorContainer: "#FFDAD6",
          background: "#000000",
          onBackground: "#E2E8F0",
          surface: "#000000",
          onSurface: "#E2E8F0",
          surfaceVariant: "#1a1a1a",
          onSurfaceVariant: "#CBD5E1",
          outline: "#94A3B8",
          outlineVariant: "#333333",
          shadow: "#000000",
          scrim: "#000000",
          inverseSurface: "#E2E8F0",
          inverseOnSurface: "#1E293B",
          inversePrimary: "#1E40AF",
          primaryFixed: "#DBEAFE",
          onPrimaryFixed: "#1E3A8A",
          primaryFixedDim: "#93C5FD",
          onPrimaryFixedVariant: "#1E40AF",
          secondaryFixed: "#CFFAFE",
          onSecondaryFixed: "#164E63",
          secondaryFixedDim: "#67E8F9",
          onSecondaryFixedVariant: "#0891B2",
          tertiaryFixed: "#FEF3C7",
          onTertiaryFixed: "#78350F",
          tertiaryFixedDim: "#FCD34D",
          onTertiaryFixedVariant: "#D97706",
          surfaceDim: "#000000",
          surfaceBright: "#1a1a1a",
          surfaceContainerLowest: "#000000",
          surfaceContainerLow: "#0a0a0a",
          surfaceContainer: "#1a1a1a",
          surfaceContainerHigh: "#262626",
          surfaceContainerHighest: "#333333",
        },
        "dark-medium-contrast": {
          primary: "#BFDBFE",
          surfaceTint: "#93C5FD",
          onPrimary: "#1E3A8A",
          primaryContainer: "#3B82F6",
          onPrimaryContainer: "#FFFFFF",
          secondary: "#A5F3FC",
          onSecondary: "#164E63",
          secondaryContainer: "#22D3EE",
          onSecondaryContainer: "#FFFFFF",
          tertiary: "#FDE68A",
          onTertiary: "#78350F",
          tertiaryContainer: "#FBBF24",
          onTertiaryContainer: "#FFFFFF",
          error: "#FFD2CC",
          onError: "#540003",
          errorContainer: "#FF5449",
          onErrorContainer: "#000000",
          background: "#0F172A",
          onBackground: "#E2E8F0",
          surface: "#0F172A",
          onSurface: "#FFFFFF",
          surfaceVariant: "#334155",
          onSurfaceVariant: "#E2E8F0",
          outline: "#94A3B8",
          outlineVariant: "#64748B",
          shadow: "#000000",
          scrim: "#000000",
          inverseSurface: "#E2E8F0",
          inverseOnSurface: "#1E293B",
          inversePrimary: "#1E3A8A",
          primaryFixed: "#DBEAFE",
          onPrimaryFixed: "#0C1B3A",
          primaryFixedDim: "#93C5FD",
          onPrimaryFixedVariant: "#1E3A8A",
          secondaryFixed: "#CFFAFE",
          onSecondaryFixed: "#083344",
          secondaryFixedDim: "#67E8F9",
          onSecondaryFixedVariant: "#155E75",
          tertiaryFixed: "#FEF3C7",
          onTertiaryFixed: "#451A03",
          tertiaryFixedDim: "#FCD34D",
          onTertiaryFixedVariant: "#92400E",
          surfaceDim: "#0F172A",
          surfaceBright: "#475569",
          surfaceContainerLowest: "#020617",
          surfaceContainerLow: "#1E293B",
          surfaceContainer: "#334155",
          surfaceContainerHigh: "#475569",
          surfaceContainerHighest: "#64748B",
        },
        "dark-high-contrast": {
          primary: "#F8FAFC",
          surfaceTint: "#93C5FD",
          onPrimary: "#000000",
          primaryContainer: "#BFDBFE",
          onPrimaryContainer: "#000000",
          secondary: "#F0FDFA",
          onSecondary: "#000000",
          secondaryContainer: "#A5F3FC",
          onSecondaryContainer: "#000000",
          tertiary: "#FFFBEB",
          onTertiary: "#000000",
          tertiaryContainer: "#FDE68A",
          onTertiaryContainer: "#000000",
          error: "#FFECE9",
          onError: "#000000",
          errorContainer: "#FFAEA4",
          onErrorContainer: "#000000",
          background: "#020617",
          onBackground: "#F1F5F9",
          surface: "#020617",
          onSurface: "#FFFFFF",
          surfaceVariant: "#334155",
          onSurfaceVariant: "#FFFFFF",
          outline: "#E2E8F0",
          outlineVariant: "#CBD5E1",
          shadow: "#000000",
          scrim: "#000000",
          inverseSurface: "#F1F5F9",
          inverseOnSurface: "#000000",
          inversePrimary: "#172554",
          primaryFixed: "#EFF6FF",
          onPrimaryFixed: "#000000",
          primaryFixedDim: "#BFDBFE",
          onPrimaryFixedVariant: "#172554",
          secondaryFixed: "#F0FDFA",
          onSecondaryFixed: "#000000",
          secondaryFixedDim: "#A5F3FC",
          onSecondaryFixedVariant: "#083344",
          tertiaryFixed: "#FFFBEB",
          onTertiaryFixed: "#000000",
          tertiaryFixedDim: "#FDE68A",
          onTertiaryFixedVariant: "#451A03",
          surfaceDim: "#020617",
          surfaceBright: "#64748B",
          surfaceContainerLowest: "#000000",
          surfaceContainerLow: "#0F172A",
          surfaceContainer: "#1E293B",
          surfaceContainerHigh: "#334155",
          surfaceContainerHighest: "#475569",
        },
      },
      fontSize: {
        "display-large": [
          "57px",
          {
            lineHeight: "64px",
          },
        ],
        "display-medium": [
          "45px",
          {
            lineHeight: "52px",
          },
        ],
        "display-small": [
          "36px",
          {
            lineHeight: "44px",
          },
        ],
        "headline-large": [
          "32px",
          {
            lineHeight: "40px",
          },
        ],
        "headline-medium": [
          "28px",
          {
            lineHeight: "36px",
          },
        ],
        "headline-small": [
          "24px",
          {
            lineHeight: "32px",
          },
        ],
        "title-large": [
          "22px",
          {
            lineHeight: "28px",
          },
        ],
        "title-medium": [
          "16px",
          {
            lineHeight: "24px",
          },
        ],
        "title-small": [
          "14px",
          {
            lineHeight: "20px",
          },
        ],
        "body-large": [
          "16px",
          {
            lineHeight: "24px",
          },
        ],
        "body-medium": [
          "14px",
          {
            lineHeight: "20px",
          },
        ],
        "body-small": [
          "12px",
          {
            lineHeight: "16px",
          },
        ],
        "label-large": [
          "14px",
          {
            lineHeight: "20px",
          },
        ],
        "label-medium": [
          "12px",
          {
            lineHeight: "16px",
          },
        ],
        "label-small": [
          "11px",
          {
            lineHeight: "16px",
          },
        ],
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      screens: {
        custom: "1100px",
        resultaHidden: "766px",
        lgMin: "947px",
      },
    },
  },
  plugins: [typography],
} satisfies Config;
